### ISSUE TITLE
Can you push your training code?

### ISSUE THREAD

**Issue by Vietdung113** [XgTu/GFA-CNN#1]
thank you for your publication, can you push your training code ?

**Comment by XgTu** [comment]
> thank you for your publication, can you push your training code ?
The training code will be only available upon the acceptance of our paper, pls keep patience.

**Comment by Vietdung113** [comment]
> > thank you for your publication, can you push your training code ?
> > The training code will be only available upon the acceptance of our paper, pls keep patience.

Thank you for your response, can you just push your TPC code?
